import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'dart:io';

class PDFService {
  static Future<File> generateDrawListPDF(
      Map<String, dynamic> drawData,
      String denomination,
      String drawNumber,
      ) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header
              pw.Header(
                level: 0,
                child: pw.Text(
                  'Pakbond Draw List',
                  style: pw.TextStyle(
                    fontSize: 24,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ),

              pw.SizedBox(height: 20),

              // Draw Information
              pw.Container(
                padding: const pw.EdgeInsets.all(10),
                decoration: pw.BoxDecoration(
                  border: pw.Border.all(color: PdfColors.black),
                ),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      'Draw Information',
                      style: pw.TextStyle(
                        fontSize: 18,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                    pw.SizedBox(height: 10),
                    _buildInfoRow('Denomination', denomination),
                    _buildInfoRow('Draw Number', drawNumber),
                    _buildInfoRow('Draw Date', drawData['drawDate'] ?? ''),
                    _buildInfoRow('City', drawData['city'] ?? ''),
                    _buildInfoRow('Expiry Date', drawData['expiryDate'] ?? ''),
                  ],
                ),
              ),

              pw.SizedBox(height: 20),

              // Prizes Sections
              if (drawData['firstPrize'] != null)
                _buildPrizeSection(
                  'First Prize',
                  drawData['firstPrize'],
                  List<String>.from(drawData['firstPrizeNumbers'] ?? []),
                ),

              pw.SizedBox(height: 15),

              if (drawData['secondPrize'] != null)
                _buildPrizeSection(
                  'Second Prize',
                  drawData['secondPrize'],
                  List<String>.from(drawData['secondPrizeNumbers'] ?? []),
                ),

              pw.SizedBox(height: 15),

              if (drawData['thirdPrize'] != null)
                _buildPrizeSection(
                  'Third Prize',
                  drawData['thirdPrize'],
                  List<String>.from(drawData['thirdPrizeNumbers'] ?? []),
                ),

              // Footer
              pw.Spacer(),
              pw.Container(
                alignment: pw.Alignment.center,
                child: pw.Text(
                  'Generated by Pakbond App',
                  style: pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey,
                  ),
                ),
              ),
            ],
          );
        },
      ),
    );

    // Save PDF
    final dir = await getApplicationDocumentsDirectory();
    final file = File('${dir.path}/Pakbond_Draw_${denomination}_$drawNumber.pdf');
    await file.writeAsBytes(await pdf.save());
    return file;
  }

  static pw.Widget _buildInfoRow(String label, String value) {
    return pw.Row(
      children: [
        pw.Expanded(
          flex: 2,
          child: pw.Text(
            '$label:',
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          ),
        ),
        pw.Expanded(
          flex: 3,
          child: pw.Text(value),
        ),
      ],
    );
  }

  static pw.Widget _buildPrizeSection(
      String title,
      Map<String, dynamic> prize,
      List<String> numbers,
      ) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.black, width: 0.5),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            title,
            style: pw.TextStyle(
              fontSize: 16,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 10),

          // Prize details table
          pw.Table(
            border: pw.TableBorder.all(),
            children: [
              pw.TableRow(
                decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                children: [
                  pw.Padding(
                    padding: const pw.EdgeInsets.all(5),
                    child: pw.Text(
                      'Count',
                      textAlign: pw.TextAlign.center,
                      style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                    ),
                  ),
                  pw.Padding(
                    padding: const pw.EdgeInsets.all(5),
                    child: pw.Text(
                      'Value',
                      textAlign: pw.TextAlign.center,
                      style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                    ),
                  ),
                  pw.Padding(
                    padding: const pw.EdgeInsets.all(5),
                    child: pw.Text(
                      'Filer',
                      textAlign: pw.TextAlign.center,
                      style:pw.TextStyle(fontWeight: pw.FontWeight.bold),
                    ),
                  ),
                  pw.Padding(
                    padding: const pw.EdgeInsets.all(5),
                    child: pw.Text(
                      'Non-Filer',
                      textAlign: pw.TextAlign.center,
                      style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                    ),
                  ),
                ],
              ),
              pw.TableRow(
                children: [
                  pw.Padding(
                    padding: const pw.EdgeInsets.all(5),
                    child: pw.Text(
                      prize['count']?.toString() ?? '-',
                      textAlign: pw.TextAlign.center,
                    ),
                  ),
                  pw.Padding(
                    padding: const pw.EdgeInsets.all(5),
                    child: pw.Text(
                      prize['value']?.toString() ?? '-',
                      textAlign: pw.TextAlign.center,
                    ),
                  ),
                  pw.Padding(
                    padding: const pw.EdgeInsets.all(5),
                    child: pw.Text(
                      prize['filer']?.toString() ?? '-',
                      textAlign: pw.TextAlign.center,
                    ),
                  ),
                  pw.Padding(
                    padding: const pw.EdgeInsets.all(5),
                    child: pw.Text(
                      prize['nonFiler']?.toString() ?? '-',
                      textAlign: pw.TextAlign.center,
                    ),
                  ),
                ],
              ),
            ],
          ),

          pw.SizedBox(height: 10),

          // Winning numbers
          if (numbers.isNotEmpty)
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'Winning Numbers:',
                  style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                ),
                pw.SizedBox(height: 5),
                pw.Wrap(
                  children: numbers.map((number) {
                    return pw.Container(
                      margin: const pw.EdgeInsets.only(right: 5, bottom: 5),
                      padding: const pw.EdgeInsets.symmetric(
                        horizontal: 8,
                        vertical: 4,
                      ),
                      decoration: pw.BoxDecoration(
                        border: pw.Border.all(color: PdfColors.black),
                        borderRadius: pw.BorderRadius.circular(4),
                      ),
                      child: pw.Text(number),
                    );
                  }).toList(),
                ),
              ],
            ),
        ],
      ),
    );
  }
}